// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMsEqX-r593wOhU5XmA0zHmFZNIQWrsE',
    appId: '1:361982142858:web:fd582903f4495cb7e3c073',
    messagingSenderId: '361982142858',
    projectId: 'vibex-51823',
    authDomain: 'vibex-51823.firebaseapp.com',
    storageBucket: 'vibex-51823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADe5X5PWZlJUWZwDtji2PaLBgXfA0c2hc',
    appId: '1:361982142858:android:7cb9720e0eeb7198e3c073',
    messagingSenderId: '361982142858',
    projectId: 'vibex-51823',
    storageBucket: 'vibex-51823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBY0uOoO4DWBWZAWpflNHA12LSKK7x-OM',
    appId: '1:361982142858:ios:bb2accfec58bb863e3c073',
    messagingSenderId: '361982142858',
    projectId: 'vibex-51823',
    storageBucket: 'vibex-51823.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBY0uOoO4DWBWZAWpflNHA12LSKK7x-OM',
    appId: '1:361982142858:ios:bb2accfec58bb863e3c073',
    messagingSenderId: '361982142858',
    projectId: 'vibex-51823',
    storageBucket: 'vibex-51823.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkMsEqX-r593wOhU5XmA0zHmFZNIQWrsE',
    appId: '1:361982142858:web:8c8af08f454e2ad6e3c073',
    messagingSenderId: '361982142858',
    projectId: 'vibex-51823',
    authDomain: 'vibex-51823.firebaseapp.com',
    storageBucket: 'vibex-51823.firebasestorage.app',
  );
}
